### ISSUE TITLE
Regex macro

### ISSUE THREAD

**Issue by danielkucera** [dvdred/zabbix-zfs-checks#1]
Hello, 

what's the point of that regex macro? 

I'm getting the right devices after calling discover
{"data":[{"{#ZFSPOOL}":"zstore"}]}

Thank you.

**Comment by dvdred** [comment]
Hello, I use the regex **to avoid making discovery of non zfs resources**. In this way, you can use this template in addition to the basic templates (eg "linux") which make their own discovery based on the similar regular expression.
