### ISSUE TITLE
RAW IO stats

### ISSUE THREAD

**Issue by danielkucera** [dvdred/zabbix-zfs-checks#2]
there is a way, how to get raw IO stats:

```
# cat /proc/spl/kstat/zfs/zstore/io 
20 3 0x00 1 80 97197853411 268614323935821
nread    nwritten reads    writes   wtime    wlentime wupdate  rtime    rlentime rupdate  wcnt     rcnt    
481047831040 2817338549248 15944997 44336169 4933387151723 15480260499887487 268614266070092 11248067361317 15480260499887487 268614266317136 0        0
```

**Comment by dvdred** [comment]
It is a good suggestion, thank you. I try to update the project including raw data!
(metrics meaning: https://fossies.org/dox/zfs-0.6.5.8/kstat_8h_source.html#l00589)

**Comment by dvdred** [comment]
I updated the monitored metrics. You can check the new options in https://github.com/dvdred/zabbix-zfs-checks/blob/master/agentside/zbx-agent-zfs.sh#L10. i will update the template, but if you have any other suggestion i will be glad to include it. :)

**Comment by dvdred** [comment]
I updated the template including new metrics, graph and trigger. Read the UPDATE.md file for instruction
